### ISSUE TITLE
Running ./config-gen on osx

### ISSUE THREAD

**Issue by Januszpl** [WeareJH/config-gen#13]
Not quite related to config-gen. more to os x and permission/zsh/rustc issue?

I have permission denied when running
./config-gen

Anyone had similar issues?

**Comment by Igloczek** [comment]
`chmod +x config-gen` solves the issue

**Comment by Januszpl** [comment]
Solution solved. `chmod + x config-en`

**Comment by Januszpl** [comment]
@shakyShane - wish I could see recording from this talk ;)
