### ISSUE TITLE
Cannot find key.pem file

### ISSUE THREAD

**Issue by natewoodbridge** [WeareJH/config-gen#18]
When I try and run the binary downloaded from the release tab I get an error saying cannot find `src/key.pm`

This is the full error:
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorStack([Error { code: 33558530, library: "system library", function: "fopen", reason: "No such file or directory", file: "bss_file.c", line: 406, data: "fopen(\'src/key.pem\',\'r\')" }, Error { code: 537346050, library: "BIO routines", function: "FILE_CTRL", reason: "system lib", file: "bss_file.c", line: 408 }, Error { code: 336265218, library: "SSL routines", function: "SSL_CTX_use_PrivateKey_file", reason: "system lib", file: "ssl_rsa.c", line: 633 }])', libcore/result.rs:945:5
`

**Comment by shakyShane** [comment]
@natewoodbridge thanks  - looks like I need to include the self-signed key/cert into the binary https://github.com/WeareJH/config-gen/blob/9f43b9f5c67df89d9af94eb8a55c5582589ee300/src/main.rs#L106-L118

**Comment by shakyShane** [comment]
@natewoodbridge for now, you can always clone this repo and run 

```
cargo run -- https://example.com --config config.yml
```

**Comment by shakyShane** [comment]
@natewoodbridge got a fix in works

**Comment by natewoodbridge** [comment]
@shakyShane Works now. Thank you!
