### ISSUE TITLE
bash: ./config-gen: is a directory

### ISSUE THREAD

**Issue by AsuraLuo** [WeareJH/config-gen#48]
when i run './config-gen http://example.com --config config-gen.yml' or './config-gen', console warning: bash: ./config-gen: is a directory

**Comment by JDreamLuo** [comment]
how to use this commod, i have used sudo chmod +x config-gen

**Comment by BenGlassAtlas** [comment]
This is caused by downloading the source, you need to download it from the first link:

![Releases_·_WeareJH_config-gen](https://user-images.githubusercontent.com/8895777/75043205-91cb7580-54b7-11ea-905a-75412d51de53.jpg)

**Comment by shakyShane** [comment]
^ thanks @BenSpace48
